acme_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeSiteBundle:Default:index }
    acme_site_sitepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeSiteBundle:Default:index }
